import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
//import GoogleAdsense from "@/app/GoogleAdsense";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={
        cn(
          inter.className,
          "w-screen h-screen flex justify-center"
        )}>
        <div className="h-screen w-full max-w-[1630px]">
          {children}
        </div>
      </body>
    </html>
  );
}
