pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-2'
        EKS_CLUSTER = 'ekstest'
        DOCKER_IMAGE = 'zshhero/petsavinghub'
        DOCKER_TAG = 'latest'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: '5aa9619d-be3b-4127-a8ee-9f153e81db9c', url: 'https://github.com/zshhero/petsavinghub.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'npm install'  // Node.js 示例
                sh 'npm test'  // 运行单元测试（如果有）
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_IMAGE:$DOCKER_TAG ."
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-credentials', url: 'https://index.docker.io/v1/']) {
                    sh "docker push $DOCKER_IMAGE:$DOCKER_TAG"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'eks-kubeconfig']) {
                    sh 'kubectl apply -f jenkins/deployment.yaml'
                    sh 'kubectl apply -f jenkins/service.yaml'
                }
            }
        }
    }
}
