import { product } from "@/constants/commonTypes";

type chewyProduct = {
  "partNumber": string,
  "parentPartNumber": string |null,
  "catalogEntryId": number,
  "name": string,
  "manufacturer": string,
  "bundleTitle": string | null,
  "href": string,
  "isBundle": boolean,
  "bundlePartNumbers": any[],
  "isChewyExclusive": boolean,
  "isDeal": boolean,
  "isGiftCard": boolean,
  "isFresh": boolean,
  "isFrozen": boolean,
  "isLiveFeed": boolean,
  "isLivePlant": boolean,
  "isNew": boolean,
  "isPrescription": boolean | null,
  "isPharmaceutical": boolean,
  "isRxVetDiet": boolean,
  "hasMoreChoices": boolean,
  "isCustomizable": boolean,
  "image": string,
  "rating": number,
  "ratingCount": number,
  "price": string,
  "autoshipPrice": null | string,
  "strikePrice": string,
  "strikePriceType": string | null,
  "strikeSavingsPct": string | null,
  "minimumAdvertisedPrice": string | null,
  "itemAnalytics": any,
  "isAd": boolean,
  "isAtf": boolean,
  "isBtf": boolean,
  "impressionTracker": string,
  "clickTracker": string,
  "inStock": boolean,
  "adPlacement": any,
  "ensembleName": string,
  "ensemblePartNumbers": any[],
  "nationalBrand": string
}

export function parseJson(rawProducts: chewyProduct[]) {
  const products: product[] = [];
  rawProducts.forEach((rawProduct) => {
    const product: product = {
      name: rawProduct.name,
      href: rawProduct.href,
      img: `https:${rawProduct.image.split(",")[0]}.jpg`,
      regularPrice: rawProduct.strikePrice || rawProduct.price,
      salesPrice: rawProduct.strikePrice ? rawProduct.price : undefined,
      promotionalMessages: rawProduct.autoshipPrice ? [`Autoship price is even lower - $${rawProduct.autoshipPrice}`] : undefined
    };
    products.push(product);
  });
  return products;
}

// https://image.chewy.com/ca/is/image/catalog/1000031342_MAIN._AC_SL600_V1700523171_.jpg
// {
//   "partNumber": "1000031342",
//   "parentPartNumber": null,
//   "catalogEntryId": 1000031342,
//   "name": "Whiskas Seafood Selections Salmon & Shrimp Flavour Natural Adult Dry Cat Food, 2-kg bag",
//   "manufacturer": "Whiskas",
//   "bundleTitle": null,
//   "href": "https://www.chewy.com/ca/whiskas-seafood-selections-salmon/dp/1000031342",
//   "isBundle": false,
//   "bundlePartNumbers": [],
//   "isChewyExclusive": false,
//   "isDeal": false,
//   "isGiftCard": false,
//   "isFresh": false,
//   "isFrozen": false,
//   "isLiveFeed": false,
//   "isLivePlant": false,
//   "isNew": false,
//   "isPrescription": null,
//   "isPharmaceutical": false,
//   "isRxVetDiet": false,
//   "hasMoreChoices": false,
//   "isCustomizable": false,
//   "image": "//image.chewy.com/ca/is/image/catalog/1000031342_MAIN,1700523171",
//   "rating": 5,
//   "ratingCount": 2,
//   "price": "9.47",
//   "autoshipPrice": "9.0",
//   "strikePrice": "9.49",
//   "strikePriceType": null,
//   "strikeSavingsPct": null,
//   "minimumAdvertisedPrice": null,
//   "itemAnalytics": {
//       "data-result-count": "4135",
//       "data-brand": "Whiskas",
//       "data-category": "1000031334",
//       "data-experience-type": "",
//       "data-id": "1000031342",
//       "data-input-query": "",
//       "data-is-customizable": "false",
//       "data-name": "Whiskas Seafood Selections Salmon & Shrimp Flavour Natural Adult Dry Cat Food, 2-kg bag",
//       "data-new-cat-entry-type": "",
//       "data-on-sale": "no",
//       "data-output-query": "",
//       "data-page-num": "5",
//       "data-price": "9.47",
//       "data-variant": "",
//       "data-deal-text": "",
//       "data-widget-id": "",
//       "data-widget-type": "",
//       "data-creative-id": "",
//       "data-widget-type-value": "",
//       "data-impression-tracker": "",
//       "data-analytics-piq-impression-id": "",
//       "data-analytics-piq-impression-payload": "",
//       "data-is-monetized": "false",
//       "data-in-stock-flag": "true"
//   },
//   "isAd": false,
//   "isAtf": false,
//   "isBtf": false,
//   "impressionTracker": "",
//   "clickTracker": "",
//   "inStock": true,
//   "adPlacement": null,
//   "ensembleName": "",
//   "ensemblePartNumbers": [],
//   "nationalBrand": "CA"
// }